server:
  port: 8000

spring:
  datasource:
    #url: jdbc:mariadb://192.168.100.30:3306/billy # 배포
    url: jdbc:mariadb://59.6.99.131:3306/billy # 로컬
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: smlab7@@
  output:
    ansi:
      enabled: always

  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 20MB

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:

  security:
    debug: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: 'smtkdals94@gmail.com'
    password: 'sm9635789'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jwt:
    secret-key: SmartMobility-Inc.Technology-Research-Center.BillieApplication-Project